ganttech/ganttech/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from ganttech import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('home.urls')),
    path('order/', include('order.urls')),
    path('user/', include('user.urls')),
    path('comment/', include('comment.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ganttech/home/urls.py
from django.urls import path
from home.views import index, get_single, get_category, get_search, test


urlpatterns = [
    path('', index, name='base'),
    path('product/<int:slug>/', get_single, name='single'),
    path('category/<int:category_id>/', get_category, name='category'),
    path('get_search/', get_search, name='search'),
    path('test/', test)
]

ganttech/home/models.py
from django.db import models
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel
from django.urls import reverse
from django.utils.safestring import mark_safe


class Category(MPTTModel):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )

    parent = TreeForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    image = models.ImageField(blank=True, upload_to='images/')
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class MPTTMeta:
        order_insertion_by = ['title']

    def get_absolute_url(self):
        return reverse('category', kwargs={"category_id": self.pk})

    def __str__(self):                           # __str__ method elaborated later in
        full_path = [self.title]                  # post.  use __unicode__ in place of
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' / '.join(full_path[::-1])

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Brand(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="brand_images/", blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Brand'
        verbose_name_plural = 'Brands'



class Color(models.Model):
    title = models.CharField(max_length=100)
    color_code = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Цвет'
        verbose_name_plural = 'Цвета'



    def __str__(self):
        return self.title

class Size(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Размер'
        verbose_name_plural = 'Размеры'




class Product(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )

    category = models.ForeignKey(Category, on_delete=models.PROTECT, null=True,  verbose_name='Наименование категории')
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    title = models.CharField(max_length=10000, verbose_name='Наименование')
    slug = models.SlugField(unique=True)
    price = models.DecimalField(max_digits=12, decimal_places=2, default=0, verbose_name='Цена')
    keywords = models.CharField(max_length=255, verbose_name='ключевые слова')
    description = models.TextField()
    detail = models.TextField()
    amount = models.IntegerField(default=0, verbose_name='Количество товара')
    minamount = models.IntegerField(default=3, blank=True, null=True, verbose_name='минимальная сумма')
    image = models.ImageField(upload_to='image')
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book', kwargs={"pk": self.pk})

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['title']


class Images(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, blank=True)
    image = models.ImageField(blank=True, upload_to='images/')
    color = models.ForeignKey(Color, on_delete=models.CASCADE, blank=True, null=True)
    size = models.ForeignKey(Size, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.title

ganttech/user/models.py
# from currencies.models import Currency
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.utils.safestring import mark_safe






class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=50)
    image = models.ImageField(blank=True, upload_to='images/users/')
    # currency = models.ForeignKey(Currency, on_delete=models.CASCADE, null=True, blank=True)


    def __str__(self):
        return self.user.username

    def user_name(self):
        return self.user.first_name + ' ' + self.user.last_name + ' [' + self.user.username + '] '

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

ganttech/home/views.py
from django.db.models import Count
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponseRedirect
from home.models import Category, Brand, Color, Size, Product, Images
from comment.models import Comment, CommentForm
from order.models import ShopCart
from django.contrib import messages



def base(request):
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)

    total = 0
    for rs in shopcart:
        total += rs.product.price * rs.quantity

    context = {
        'shopcart': shopcart,
        'total': total
    }

    return render(request, 'base.html', context)




def index(request):
    category = Category.objects.all()
    category_el = Category.objects.first()
    product = Product.objects.all()
    product_circle = Product.objects.order_by('?')[:6]
    category_circle = Category.objects.order_by('?')[:7]

    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)

    total = 0
    for rs in shopcart:
        total += rs.product.price * rs.quantity


    context = {
        'category': category,
        'product': product,
        'product_circle': product_circle,
        'category_circle': category_circle,
        'category_el': category_el,
        'shopcart': shopcart,
        'total': total
    }

    return render(request, 'index.html', context)


def get_search(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        product_search = Product.objects.filter(title__contains=searched)


        return render(request, 'search.html', {'searched': searched, 'product_search': product_search})
    else:

        return render(request, 'search.html')




def get_single(request, slug:int):
    product_single = get_object_or_404(Product, id=slug)
    category = Category.objects.all()
    images = Images.objects.filter(product_id=slug)
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)

    total = 0
    for rs in shopcart:
        total += rs.product.price * rs.quantity


    product_circle = Product.objects.order_by('?')[:7]

    comments = Comment.objects.filter(product=product_single)

    if request.method == 'POST':  # check post
        form = CommentForm(request.POST)
        if form.is_valid():
            data = Comment()  # create relation with model
            data.username = form.cleaned_data['username']
            data.comment = form.cleaned_data['comment']
            data.rate = form.cleaned_data['rate']
            data.ip = request.META.get('REMOTE_ADDR')
            data.product_id = slug
            current_user = request.user
            data.user_id = current_user.id
            data.save()  # save data to table
            messages.success(request, "Your review has ben sent. Thank you for your interest.")
            return HttpResponseRedirect(reverse('single', args=[slug]))
    else:
        form = CommentForm()


    context = {
        'product_single': product_single,
        'category': category,
        'images': images,
        'product_circle': product_circle,
        'comments': comments,
        'form': form,
        'shopcart': shopcart,
        'total': total,
    }

    return render(request, 'product.html', context)


def is_valid_queryparam(param):
    return param != '' and param is not None



def get_category(request, category_id):
    category = Category.objects.get(pk=category_id)
    products = Product.objects.filter(category_id=category_id)
    categories = Category.objects.all().annotate(posts_count=Count('product'))
    brands = Brand.objects.all()
    view_count_min = request.GET.get('view_count_min')
    view_count_max = request.GET.get('view_count_max')
    brand = request.GET.get('brand')


    for cat in categories:
        print(cat.posts_count)



    if is_valid_queryparam(view_count_min):
        products = products.filter(price__gte=view_count_min)

    if is_valid_queryparam(view_count_max):
        products = products.filter(price__lt=view_count_max)

    if is_valid_queryparam(brand):
        products = products.filter(brand__name=brand)

    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)

    total = 0
    for rs in shopcart:
        total += rs.product.price * rs.quantity


    context = {
        'products': products,
        'category': category,
        'brands': brands,
        'categories': categories,
        'shopcart': shopcart,
        'total': total
    }
    return render(request, 'category.html', context)


def test(request):
    return render(request, 'test.html')

ganttech/home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
	<title>Интернет магазин - GantTech в Ашхабаде</title>
	<meta charset="UTF-8">
	<meta name="description" content="Интернет магазин GantTech в Ашхабаде, Туркменистан. Бесплатная доставка на дом и самовывоз из магазина GantTech по Ашхабаду. Смартфоны, мобильные телефоны, apple, iphone, планшеты, ноутбуки, компьютеры, мониторы, принтеры, телевизоры, флешки">
	<meta name="keywords" content="Интернет магазин GantTech, магазин электроники, доставка товаров.">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="{% static 'img/favicon.ico' %}" rel="shortcut icon"/>

	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,300i,400,400i,700,700i" rel="stylesheet">


	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/flaticon.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/animate.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/style.css' %}"/>


	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Header section -->
	<header class="header-section">
		<div class="header-top">
			<div class="container">
				<div class="row">
					<div class="col-lg-2 text-center text-lg-left">
						<!-- logo -->
						<a href="/" class="site-logo">
							<img src="{% static '' %}img/logo.png" alt="">
						</a>
					</div>
					<div class="col-xl-6 col-lg-5">
						<form class="header-search-form" method="post" action="{% url 'search' %}">
                            {% csrf_token %}
							<input type="text" placeholder="Search on divisima ...."  name="searched">
							<button type="submit"><i class="flaticon-search"></i></button>
						</form>
					</div>
					<div class="col-xl-4 col-lg-5">
						<div class="user-panel">
							<div class="up-item">
                                {% if user.id is not None %}
                                    <a href="{% url 'user_index' %}">{{ user.username }}</a> In or<a href="{% url 'logout' %}"> Выход</a>
                                {% else %}
                                    <i class="flaticon-profile"></i>
								    <a href="{% url 'login_form' %}">Sign</a> In or <a href="{% url 'register' %}">Create Account</a>
                                {% endif %}
							</div>
							<div class="up-item">
								<div class="shopping-card">
									<i class="flaticon-bag"></i>
									<span>{{ total }}</span>
								</div>
								<a href="{% url 'shopcart' %}">Shopping Cart</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<nav class="main-navbar">
			<div class="container">
				<!-- menu -->
				<ul class="main-menu">
					<li><a href="/">Home</a></li>
					<li><a href="">Женщинам</a></li>
					<li><a href="#">Мужчинам</a></li>
					<li><a href="#">Ювелирные изделия
						<span class="new">New</span>
					</a></li>
					<li><a href="#">Обувь</a>
						<ul class="sub-menu">
							<li><a href="#">Кроссовки</a></li>
							<li><a href="#">Сандалии</a></li>
							<li><a href="#">Официальная обувь</a></li>
							<li><a href="#">Сапоги</a></li>
							<li><a href="#">Шлепки</a></li>
						</ul>
					</li>
					<li><a href="#">Category</a>
						<ul class="sub-menu">
							<li><a href="./product.html">Product Page</a></li>
							<li><a href="./category.html">Category Page</a></li>
							<li><a href="./cart.html">Cart Page</a></li>
							<li><a href="./checkout.html">Checkout Page</a></li>
							<li><a href="./contact.html">Contact Page</a></li>
						</ul>
					</li>
					<li><a href="">asd</a></li>
				</ul>
			</div>
		</nav>
	</header>
	<!-- Header section end -->


        {% block content %}

        {% endblock %}





	<!-- Footer section -->
	<section class="footer-section">
		<div class="container">
			<div class="footer-logo text-center">
				<a href="index.html"><img src="{% static '' %}img/logo-light.png" alt=""></a>
			</div>
			<div class="row">
				<div class="col-lg-3 col-sm-6">
					<div class="footer-widget about-widget">
						<h2>About</h2>
						<p>Donec vitae purus nunc. Morbi faucibus erat sit amet congue mattis. Nullam frin-gilla faucibus urna, id dapibus erat iaculis ut. Integer ac sem.</p>
						<img src="{% static '' %}img/cards.png" alt="">
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="footer-widget about-widget">
						<h2>Questions</h2>
						<ul>
							<li><a href="">About Us</a></li>
							<li><a href="">Track Orders</a></li>
							<li><a href="">Returns</a></li>
							<li><a href="">Jobs</a></li>
							<li><a href="">Shipping</a></li>
							<li><a href="">Blog</a></li>
						</ul>
						<ul>
							<li><a href="">Partners</a></li>
							<li><a href="">Bloggers</a></li>
							<li><a href="">Support</a></li>
							<li><a href="">Terms of Use</a></li>
							<li><a href="">Press</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="footer-widget about-widget">
						<h2>Questions</h2>
						<div class="fw-latest-post-widget">
							<div class="lp-item">
								<div class="lp-thumb set-bg" data-setbg="img/blog-thumbs/1.jpg"></div>
								<div class="lp-content">
									<h6>what shoes to wear</h6>
									<span>Oct 21, 2018</span>
									<a href="#" class="readmore">Read More</a>
								</div>
							</div>
							<div class="lp-item">
								<div class="lp-thumb set-bg" data-setbg="img/blog-thumbs/2.jpg"></div>
								<div class="lp-content">
									<h6>trends this year</h6>
									<span>Oct 21, 2018</span>
									<a href="#" class="readmore">Read More</a>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="footer-widget contact-widget">
						<h2>Questions</h2>
						<div class="con-info">
							<span>C.</span>
							<p>Your Company Ltd </p>
						</div>
						<div class="con-info">
							<span>B.</span>
							<p>1481 Creekside Lane  Avila Beach, CA 93424, P.O. BOX 68 </p>
						</div>
						<div class="con-info">
							<span>T.</span>
							<p>+99362322145</p>
						</div>
						<div class="con-info">
							<span>E.</span>
							<p>robertdjango23@gmail.com</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="social-links-warp">
			<div class="container">
				<div class="social-links">
					<a href="" class="instagram"><i class="fa fa-instagram"></i><span>instagram</span></a>
					<a href="" class="google-plus"><i class="fa fa-google-plus"></i><span>g+plus</span></a>
					<a href="" class="pinterest"><i class="fa fa-pinterest"></i><span>pinterest</span></a>
					<a href="" class="facebook"><i class="fa fa-facebook"></i><span>facebook</span></a>
					<a href="" class="twitter"><i class="fa fa-twitter"></i><span>twitter</span></a>
					<a href="" class="youtube"><i class="fa fa-youtube"></i><span>youtube</span></a>
					<a href="" class="tumblr"><i class="fa fa-tumblr-square"></i><span>tumblr</span></a>
				</div>

<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
<p class="text-white text-center mt-5">Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a></p>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->

			</div>
		</div>
	</section>
	<!-- Footer section end -->



	<!--====== Javascripts & Jquery ======-->
	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/jquery.nicescroll.min.js' %}"></script>
	<script src="{% static 'js/jquery.zoom.min.js' %}"></script>
	<script src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

ganttech/home/templates/blank.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

		<title>Electro - HTML Ecommerce Template</title>

 		<!-- Google font -->
 		<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

 		<!-- Bootstrap -->
 		<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>

 		<!-- Slick -->
 		<link type="text/css" rel="stylesheet" href="{% static 'css/slick.css' %}"/>
 		<link type="text/css" rel="stylesheet" href="{% static 'css/slick-theme.css' %}"/>

 		<!-- nouislider -->
 		<link type="text/css" rel="stylesheet" href="{% static 'css/nouislider.min.css' %}"/>

 		<!-- Font Awesome Icon -->
 		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

 		<!-- Custom stlylesheet -->
 		<link type="text/css" rel="stylesheet" href="{% static 'css/style/style.css' %}"/>

 		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
 		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
 		<!--[if lt IE 9]>
 		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
 		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
 		<![endif]-->

    </head>
	<body>


		<!-- BREADCRUMB -->
		<div id="breadcrumb" class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
						<h3 class="breadcrumb-header">Regular Page</h3>
						<ul class="breadcrumb-tree">
							<li><a href="/">Home</a></li>
							<li class="active">Blank</li>
						</ul>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /BREADCRUMB -->

		<!-- SECTION -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">

                    <div class="col-md-12">
                        <div class="order-summary clearfix">
                            <div class="section-title">
                                <h3 class="title">Order Complated</h3>
                            </div>
                            <hr>
                            <h2>Dear  {{ user.first_name }} {{  user.last_name }}</h2>
                            <hr>
                            <h3>Your order is completed</h3>
                            <h3>Order Code : {{ ordercode }}</h3>
                            <h3>Thank You</h3>
                            <hr>

                        </div>

                    </div>

				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /SECTION -->

		<!-- NEWSLETTER -->
		<div id="newsletter" class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /NEWSLETTER -->


		<!-- jQuery Plugins -->
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/slick.min.js' %}"></script>
		<script src="{% static 'js/nouislider.min.js' %}"></script>
		<script src="{% static 'js/jquery.zoom.min.js' %}"></script>
		<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

ganttech/home/templates/checkout.html
{% extends 'base.html' %}
{% load static %}



{% block content %}


	<!-- Page info -->
	<div class="page-top-info">
		<div class="container">
			<h4>Your cart</h4>
			<div class="site-pagination">
				<a href="/">Home</a> /
				<a href="#">Your cart</a>
			</div>
		</div>
	</div>
	<!-- Page info end -->


	<!-- checkout section  -->
	<section class="checkout-section spad">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 order-2 order-lg-1">
					<form class="checkout-form" method="post">
                        {% csrf_token %}
						<div class="cf-title">Billing Address</div>
						<div class="row address-inputs">
							<div class="col-md-12">
								<input type="text" placeholder="First name:" name="first_name"  value="{{ user.first_name }}">
								<input type="text" placeholder="Last name:" name="last_name"  value="{{ user.last_name }}">
								<input type="text" placeholder="Address:" name="address" value="{{ profile.address }}">
								<input type="text" placeholder="Phone:"  name="phone"  value="{{ profile.phone }}">
                                <input type="text" placeholder="Country:" name="country"   id="id_country" value="{{ profile.country }}"">
							</div>
							<div class="col-md-6">
								<p><label for="id_city">City:</label>
                                <select name="city" class="input" id="id_city">
                                    <option value="{{ profile.city }}" selected>{{ profile.city }}</option>
                                    <option value="Ашхабад">Ашхабад</option>
                                    <option value="Аннау">Аннау</option>
                                    <option value="Балканабад">Балканабад</option>
                                    <option value="Дашогуз">Дашогуз</option>
                                    <option value="Мары">Мары</option>
                                    <option value="Туркменабад">Туркменабад</option>
                                </select></p>
							</div>
						</div>
						<div class="cf-title">Payment</div>
						<ul class="payment-list">
							<li>Paypal<a href="#"><img src="{% static '' %}img/paypal.png" alt=""></a></li>
							<li>Credit / Debit card<a href="#"><img src="{% static '' %}img/mastercart.png" alt=""></a></li>
							<li>Pay when you get the package</li>
						</ul>
						<button class="site-btn submit-order-btn"><a>Place Order</a></button>
					</form>
				</div>
				<div class="col-lg-4 order-1 order-lg-2">
					<div class="checkout-cart">
						<h3>Your Cart</h3>
						<ul class="product-list">
                          {% for sh in shopcart %}
                                <li>
                                    <div class="pl-thumb"><a href="{% url 'single' sh.product.id %}"><img src="{{ sh.product.image.url }}" alt=""></a></div>
                                    <h6>{{ sh.product.title|truncatechars:15 }}</h6>
                                    <p>${{ sh.price }}</p>
                                    <p>Количества товара: {{ sh.quantity }}</p>
                                </li>
                          {% endfor %}
						</ul>
						<ul class="price-list">
							<li>Total<span>{{ total }}</span></li>
							<li>Shipping<span>free</span></li>
							<li class="total">Total<span>{{ total }}</span></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- checkout section end -->

{% endblock %}

ganttech/home/templates/search.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
{% if searched %}
	<section class="product-filter-section">
		<div class="container">
			<div class="section-title">
				<h2 style="margin-top: 25px">{{ searched }}</h2>
			</div>
			<div class="row">
                {% for pro in product_search %}
				    <div class="col-lg-3 col-sm-6">
					<div class="product-item">
						<div class="pi-pic">
							<a href="{% url 'single' pro.id %}"><img src="{{ pro.image.url }}" alt="" style="height: 400px"></a>
							<div class="pi-links">
								<a href="#" class="add-card"><i class="flaticon-bag"></i><span>ADD TO CART</span></a>
								<a href="#" class="wishlist-btn"><i class="flaticon-heart"></i></a>
							</div>
						</div>
						<div class="pi-text">
							<h6>{{ pro.price }}</h6>
							<p>{{ pro.title|truncatechars:23 }}</p>
						</div>
					</div>
				</div>
                {% endfor %}

			</div>
			<div class="text-center pt-5">
				<button class="site-btn sb-line sb-dark">LOAD MORE</button>
			</div>
		</div>
	</section>
{% else %}
    <h1>Ошибка поиска</h1>
{% endif %}

{% endblock %}